### ISSUE TITLE
@XYenon 请在中国零学院网站内保留原始版权信息

### ISSUE THREAD

**Issue by lin-toto** [lin714093880/chtholly-ac#3]
另外你在是用别人的设计的时候至少应该先问一下。

我会同意，但是这是一种礼貌。

以及保留原始版权信息也是。

@XYenon

**Comment by XYenon** [comment]
抱歉，我没有做这个的经验，我会尽快修改的。

发送自 Windows 10 版邮件应用

发件人: Toto Lin
发送时间: 2017年12月13日 0:28
收件人: lin714093880/chtholly-ac
抄送: XYenon; Mention
主题: [lin714093880/chtholly-ac] @XYenon 请在中国零学院网站内保留原始版权信息 (#3)

另外你在是用别人的设计的时候至少应该先问一下。
我会同意，但是这是一种礼貌。
以及保留原始版权信息也是。
@XYenon
