### ISSUE TITLE
学习珂学家

### ISSUE THREAD

**Issue by dmcimi** [lin714093880/chtholly-ac#7]
亲爱的lin_toto：   
      您好！前来咨询是否能使用您的源代码。（我看到了您的https://www.chtholly.ac.cn/站点，我也想建个，所以直接用了您的源码库，建了https://miyazono.kaori.ml/。我在这个页面加了首歌，我心血来潮花了些时间来做，困死我啦！。求回复多有打扰。>-< ）

**Comment by lin-toto** [comment]
留名就可以，虽然我打不开你的站。不过现在没有在维护这个项目了
